### ISSUE TITLE
Example: How to create and register a subliminal provider extension.

### ISSUE THREAD

**Issue by etherealite** [Diaoul/subliminal#1177]
If you are like me, you want to make your own provider but you don't want to fork or wrap subliminal.

For anyone wondering how to make their own provider 'extension', you may have noticed that documentation for this is a placeholder:
[https://subliminal.readthedocs.io/en/latest/api/extensions.html](https://subliminal.readthedocs.io/en/latest/api/extensions.html)
```markdown
**Extensions
Extension managers for the providers, refiners and language converters.
```

But don't fret, after many trials and tribulations I have figured out how to perform the magical incantations necessary to make an extension. Let my own suffering be your salvation and read on...

All you have to do is make an entry in your pyproject.toml like so:
```toml
[project.entry-points."subliminal.providers"]
dummy = "ihatestevedore.dummyprovider:DummyProvider"
```

In this example, your package name is `ihatestevedore` and it has a module named `dummyprovider` containing your provider class definition. The entry name that you assign (left side of the '=') is arbitrary and can be whatever you want. You can then create your package layout like so:
```
/path/to/extension/ihatestevedore
└───ihatestevedore
    │   dummyprovider.py
```

Where you implement the `DummyProvider` class in the dummyprovider module:
```python
from subliminal import Provider

class DummyProvider(Provider):
    pass
```

Here is what a complete project.toml might look like:

```toml
[project]
name = "ihatestevedore"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "subliminal>=2.2.1",
]

[project.entry-points."subliminal.providers"]
dummy = "ihatestevedore.dummyprovider:DummyProvider"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
```

After installing your package, there should be an `entry_points.txt` within its home in the site-packages directory:
```
$ ls python/Lib/site-packages/ihatestevedore-0.1.0.dist-info
direct_url.json
entry_points.txt
INSTALLER
METADATA
RECORD
REQUESTED
WHEEL
```

It should look like:
```toml
[subliminal.providers]
dummy = ihatestevedore.dummyprovider:DummyProvider
````

Now your extension should be available for discovery by subliminal and you can follow the rest of the docs and examples concerning making your own provider.

More reading on how this works:
* making plugins with stevedore https://docs.openstack.org/stevedore/latest/user/tutorial/creating_plugins.html
* python toml entrypoints spec https://packaging.python.org/en/latest/specifications/entry-points/#entry-points
* subliminal's wrapper of stevedore https://github.com/Diaoul/subliminal/blob/2.2.1/subliminal/extensions.py
